In [1]:
# Numpy assignment
import numpy as np

In [25]:
# Random array
# max value
# min valye
# mean row or column
# reshape
# multiply
# odd numbers
# identity
# mean and standard deviation
# multiplication between two arrays
# Replace all odd numbers with -1
# indices of the maximum and minimum values.


In [2]:
# 1- Create a numpy array of shape (3, 4) and assign random integers between 1 and 10 to every element.
#
a = [[1,2,3,9],[4,5,6,8], [7,10,6,8]]
a_np = np.array(a)
a_np

array([[ 1,  2,  3,  9],
       [ 4,  5,  6,  8],
       [ 7, 10,  6,  8]])

In [3]:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
arr = np.random.randint(1,11, size=(3,4))
arr

array([[10,  9,  1, 10],
       [ 4,  9,  8,  8],
       [ 8,  8,  8,  1]])

In [4]:
a_np.shape

(3, 4)

In [5]:
# 2- Find the maximum value in the array created in step 1.
#
np.max(a_np)

10

In [6]:
# 3-a Calculate the mean value of each column in the array.


a = a_np.mean(axis = 0) # column
rounded_array = np.round(a , decimals=2)
rounded_array

array([4.  , 5.67, 5.  , 8.33])

In [7]:
# 3-b Calculate the mean value of each row in the array.
np.mean(a_np , axis = 1) # row

array([3.75, 5.75, 7.75])

In [8]:
# 4- Reshape the array from step 1 into a shape of (2, 6).
np.reshape(a_np,(2,6))

array([[ 1,  2,  3,  9,  4,  5],
       [ 6,  8,  7, 10,  6,  8]])

In [9]:

# 5- Multiply each element in the array by 2.
a_np*2


array([[ 2,  4,  6, 18],
       [ 8, 10, 12, 16],
       [14, 20, 12, 16]])

In [10]:
# 6- Create a numpy array with values ranging from 0 to 9. Extract the odd numbers from the array.
z1 = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
arr_z = np.array(z1)
odd_num = arr_z[arr_z%2 != 0]
print(odd_num)

[1 3 5 7 9]


In [11]:
# 7- Create a 3x3 identity matrix using numpy.
a= np.identity(3,dtype='int32')
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
# 8- Create a 5x5 array with random values and normalize it 
# (subtract the mean and divide by the standard deviation of the array).
random_array = np.random.rand(5,5)
random_array

array([[0.34758273, 0.38200875, 0.41590441, 0.66639986, 0.40309817],
       [0.44814336, 0.84812593, 0.17436928, 0.04839129, 0.90844623],
       [0.11654039, 0.82539142, 0.81710944, 0.68155576, 0.62709834],
       [0.67860427, 0.18608174, 0.03558394, 0.07775134, 0.70364441],
       [0.51930056, 0.36898214, 0.85159274, 0.44063002, 0.99821236]])

In [13]:
mean = np.mean(random_array)
mean

0.5028219553416917

In [14]:
std = np.std(random_array)
std

0.28587989405431075

In [15]:
# Normalize the array
normalized_arr = (random_array - mean) / std

print(normalized_arr)


[[-0.54302254 -0.42260126 -0.3040352   0.57219102 -0.34883105]
 [-0.19126422  1.20786381 -1.14891841 -1.58958597  1.41886256]
 [-1.35120228  1.12833911  1.09936895  0.62520591  0.43471536]
 [ 0.6148817  -1.10794856 -1.63438571 -1.48688529  0.70247143]
 [ 0.05764171 -0.46816799  1.21999059 -0.21754567  1.73286201]]


In [16]:
# 9- Perform element-wise multiplication between two arrays of the same shape.
a = [[1,2,3,4],[4,5,6,7],[10,7,8,9]]
a_array1 = np.array(a)
a_array1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [10,  7,  8,  9]])

In [17]:
b = [[2,3,2,4],[2,4,2,1],[10,2,3,2]]
a_array2 = np.array(b)
a_array2

array([[ 2,  3,  2,  4],
       [ 2,  4,  2,  1],
       [10,  2,  3,  2]])

In [18]:
a_array3 = a_array1*a_array2
a_array3

array([[  2,   6,   6,  16],
       [  8,  20,  12,   7],
       [100,  14,  24,  18]])

In [19]:
# 10 - Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).
a_array3/2.54

array([[ 0.78740157,  2.36220472,  2.36220472,  6.2992126 ],
       [ 3.1496063 ,  7.87401575,  4.72440945,  2.75590551],
       [39.37007874,  5.51181102,  9.4488189 ,  7.08661417]])

In [20]:
# 11 - Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1.

import numpy as np

# Create a 1D array of numbers from 0 to 9
arr = np.arange(10)

# Replace odd numbers with -1
arr[arr % 2 != 0] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
# 12 - Create a 2D array with random values and find the indices of the maximum and minimum values.
arr = np.random.randn(3,4)
arr

array([[ 1.05638431,  1.09449841, -0.02917503, -0.0823883 ],
       [-0.60959336,  1.41011003,  0.45373827,  1.20859757],
       [-0.00401922, -0.28480499, -0.86045229, -1.72013865]])

In [22]:
max_index = np.unravel_index(np.argmax(arr), arr.shape)


In [23]:
min_index = np.unravel_index(np.argmin(arr), arr.shape)

In [24]:

print("Array:")
print(arr)
print("Maximum value index:", max_index)
print("Minimum value index:", min_index)

Array:
[[ 1.05638431  1.09449841 -0.02917503 -0.0823883 ]
 [-0.60959336  1.41011003  0.45373827  1.20859757]
 [-0.00401922 -0.28480499 -0.86045229 -1.72013865]]
Maximum value index: (1, 1)
Minimum value index: (2, 3)
